question_data = [
    {"text": "You can get a license to legally hunt unicorns in Michigan.", "answer": True},
    {"text": "Chewing gum can boost your concentration.", "answer": True},
    {"text": "A regular internet user has three social media accounts.", "answer": False},
    {"text": "Laughing 100 times provides the equivalent of 15 minutes of exercise on a stationary bike.",
     "answer": True},
    {"text": "YouTube was founded on Valentine’s Day.", "answer": True},
    {"text": "Leaving mascara on will make your eyelashes fall out.", "answer": True},
    {"text": "Johnny Depp has a Jack tattoo in honor of the Pirates of the Caribbean movie series.", "answer": False},
    {"text": "The actors were given fake scripts while filming Avengers: Infinity War.", "answer": True},
    {"text": "The ostrich has the largest eye in the world.", "answer": False},
    {"text": "Milk is 87% water.", "answer": True},
    {"text": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.", "answer": False},
    {"text": "Gumbo is a stew that originated in Louisiana.", "answer": True},
    {"text": "French is an official language in Canada.", "answer": True},
    {"text": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.", "answer": False},
    {"text": "Nutella is produced by the German company Ferrero.", "answer": False},
    {"text": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.", "answer": False},
    {"text": "Bulls are attracted to the color red.", "answer": False},
    {"text": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.", "answer": True},
    {"text": "The Sun rises from the North.", "answer": False},
    {"text": "The color orange is named after the fruit.", "answer": True},
    {"text": "On average, at least 1 person is killed by a drunk driver in the United States every hour.", "answer": True},
    {"text": "Pluto is a planet.", "answer": False},
    {"text": "When you cry in space, your tears stick to your face.", "answer": True},
    {"text": "The Lego Group was founded in 1932.", "answer": True},
    {"text": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.", "answer": True},
    {"text": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.", "answer": True},
    {"text": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.", "answer": False},
    {"text": "The National Animal of Scotland is the Unicorn.", "answer": True},
    {"text": "A pasodoble is a type of Italian pasta sauce.", "answer": False},
    {"text": "Slovakia is a member of European Union-", "answer": True}
  ]
